development:
  adapter: postgresql
  encoding: unicode
  database: MoviePlace_development
  pool: 5
  username: movieplace
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: MoviePlace_test
  pool: 5
  username: movieplace
  password: password