# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e0b6ac3bce364e377e489bb4b9dc5d1502d1669e0099baa7612b1aadb1bf68056fe8246d32911818e1d6dbd0306f64866cf7af15eda8a6ed6c3bf73ea921c6e

test:
  secret_key_base: f894f77fd686026cbc9a4ab84b5e065a1ee9e70c6002d3f1899a93887682ac1ec7f26e15421effb945c067e68f0fb104d5de8477af1b0a0772d24f23031bc6b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
